language: python
python:
  - "3.12"
# Possible operating systems
os:
  - linux
  - osx
  - windows
install:
  # Conda instalation
  - |
    case "$(uname)" in
      "Linux")
        wget -O Miniconda3-Linux.sh https://repo.anaconda.com/miniconda/Miniconda3-py312_24.9.2-0-Linux-x86_64.sh
        bash Miniconda3-Linux.sh -b -p $HOME/miniconda
        ;;
      "Darwin")
        wget -O Miniconda3-MacOSX.sh https://repo.anaconda.com/miniconda/Miniconda3-py312_24.9.2-0-MacOSX-x86_64.sh
        bash Miniconda3-MacOSX.sh -b -p $HOME/miniconda ;;
      "MINGW"*|"MSYS"*|"CYGWIN"*)
        wget -O Miniconda3-Windows.exe https://repo.anaconda.com/miniconda/Miniconda3-py312_24.9.2-0-Windows-x86_64.exe
        ./Miniconda3-Windows.exe /S /D=C:\\Miniconda3 ;;
      *)
        echo "Unsupported OS" ;;
    esac
  # Conda activation and configuration
  - source "$HOME/miniconda/etc/profile.d/conda.sh" || source /c/Miniconda3/Scripts/activate
  - conda init
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Debugging conda
  - conda info -a
  # Creating an environment with Conda
  - conda config --prepend channels conda-forge
  - conda create -n routerl
  - conda activate routerl
  # SUMO instalation
  - |
    case "$(uname)" in
      "Linux")
        sudo add-apt-repository ppa:sumo/stable;
        sudo apt-get update;
        sudo apt-get install sumo sumo-tools sumo-doc ;;
      "Darwin")
        brew install sumo ;;
      "MINGW"*|"MSYS"*|"CYGWIN"*)
        winget install --name sumo ;;
      *)
        echo "Unsupported OS";;
    esac
  # Installing dependencies
  - pip install -r requirements.txt
  - pip install coveralls
# Running tests
script:
 - python -m unittest tests/RouteRL_test.py
 - coverage run -m unittest tests/RouteRL_test.py
# Sending cover raport
after_success:
 - coveralls