name: docs_pages_workflow

on:
  push:
    branches: [ main ]  # Triggers the workflow on main branch

permissions:
  contents: write

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx sphinx-rtd-theme myst-parser furo torch "numpy==2.0.2" scipy pandas prettytable traci gymnasium pettingzoo janux
          python -m pip install torchrl polars seaborn networkx matplotlib beautifulsoup4

      - name: Build Sphinx documentation
        run: |
          make -C docs clean   # Clean previous builds
          make -C docs html    # Build HTML files
          ls docs/_build/html  # Confirm output files in _build/html

      - name: Verify output files
        run: |
          cat docs/_build/html/index.html  # Check the index.html file's initial lines

      - name: Deploy to GitHub Pages
        run: |
          cd docs/_build/html              # Change to the built HTML directory
          touch .nojekyll                   # Disable Jekyll
          git init
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Deploy documentation to GitHub Pages"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push --force origin HEAD:gh-pages
