name: docs_pages_workflow

on:
  push:
    branches: [ main ]  # Triggers the workflow when pushing to the main branch

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # You can adjust this version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme
          python -m pip install myst-parser  # To support Markdown files

      - name: Build Sphinx documentation
        run: |
          make -C docs clean   # Clean previous builds
          make -C docs html    # Build HTML from Sphinx

      - name: Deploy to GitHub Pages
        run: |
          cd docs/_build/html  # Navigate to the built HTML files
          touch .nojekyll      # Disable Jekyll to serve raw HTML/CSS
          git init             # Initialize a new Git repo in the build folder
          git add .
          git commit -m "Deploy documentation to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages